<img src="https://ga-dash.s3.amazonaws.com/production/assets/logo-9f88ae6c9c3871690e33280fcf557f33.png" style="float: left; margin: 10px;"> 
# Numpy Lab

---
Week 1 | Lab 1.9


# Instructions
Fill in the functions found in the provided numpy_exercise.py file.  A test file is provided to check your answers (that is the `test_numpy_exercise.pyc` file).  
To run your code through the test, open a terminal window in the director you are working in, and type in

```shell
$ nosetests test_numpy_exercise.pyc
```

## Outline

1. Matrix vs Vectors  [questions one through eight]
2. Scalar Operations [questions nine through 12]
3. Matrix Vector Multiplication [questions 13-16]
4. Matrix Matrix Multiplication [questions 17 and 18]
5. Elementwise Matrix Operations [questions 19-24]

This will cover all of the basic operations you can do with matrices, as well as some properties of linear algebra with relevant machine learning.

For nearly all of our matrix operations, we will be using a python library named `numpy`

Numpy basically takes native python data structures, like lists, and gives them super math powers. So  operations that would be very difficult when using a regular python list, is a one liner when using numpy.  

```
import numpy as np

row_vector = np.arange(0, 10, 1).reshape(1, 10)

print row_vector
>>> [[0 1 2 3 4 5 6 7 8 9]]

print row_vector.shape
>>> (1, 10)

col_vector = np.linspace(100, 300, 3).reshape(3,1)

print col_vector
>>> [[ 100.]
    [ 200.]
    [ 300.]]

print col_vector.shape
>>> (3, 1)
```

In [6]:
import numpy as np
def thirteen():
    '''
    Create column vector with 3 ints, called as column_vector.
    Create a row vector with 3 ints, called as row_vector.
    Create 3 x 3 square matrix called and square_matrix:
    Return as column_vector, row_vector, square_matrix (IN THAT ORDER)
    '''
    column_vector = np.arange(1,4).reshape(3,1)
    row_vector = np.arange(1,4)
    square_matrix = column_vector * square_matrix
    return column_vector, row_vector, square_matrix
array1

NameError: name 'array1' is not defined

In [7]:
np.arange(0.5, 10, 1)

array([ 0.5,  1.5,  2.5,  3.5,  4.5,  5.5,  6.5,  7.5,  8.5,  9.5])

In [8]:
def nine():
    '''
    INPUT: None
    OUTPUT: A numpy array with values [ [0,1,2,3,4,5,6,7,8,9] ]
    Create this numpy array (called V): [ [0,1,2,3,4,5,6,7,8,9] ]
    '''
    return np.arange(0, 10)
V = nine()

def ten(V):
    '''
    INPUT: V ( matrix from nine() )
    OUTPUT: [[ 0.5  1.5  2.5  3.5  4.5  5.5  6.5  7.5  8.5  9.5]]
    Do a scalar addition by 0.5 to V.
    '''
    return V + np.array(0.5)

print ten(V)

def twelve(V):
    '''
    INPUT: V ( matrix from nine() )
    OUTPUT: answer = V+B
    Create a 1 by 10 vector 'B',
    that when added to V,  will yeild the same results as function ten
    V + B = [[ 0.5  1.5  2.5  3.5  4.5  5.5  6.5  7.5  8.5  9.5]]
    Return your answer
    '''

    B = np.ones(10) * 0.5
    print B
    return V + B

print twelve(V)


[ 0.5  1.5  2.5  3.5  4.5  5.5  6.5  7.5  8.5  9.5]
[ 0.5  0.5  0.5  0.5  0.5  0.5  0.5  0.5  0.5  0.5]
[ 0.5  1.5  2.5  3.5  4.5  5.5  6.5  7.5  8.5  9.5]


In [9]:
column_vector = np.arange(1,4).reshape(3,1)
row_vector = np.arange(4,7)
square_matrix = column_vector * row_vector
print column_vector
print row_vector
print square_matrix

[[1]
 [2]
 [3]]
[4 5 6]
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


In [13]:
np.random.random((2,3))

array([[ 0.77925527,  0.27853802,  0.79458753],
       [ 0.93823498,  0.35864384,  0.52780509]])